### ISSUE TITLE
Crashes when trying to enable on MacOS (Intel)

### ISSUE THREAD

**Issue by ksweetie** [ionthedev/ReSprytile#25]
MacOS Sonoma (Intel)
Blender 4.1.1
ReSprytile 1.0.3

It installs fine, but when I try to enable, it crashes with these messages. I've tried renaming the folder/zip, like some other comments have mentioned. I also tried to pip install gpu in blender's python, but didn't get too far down that path.

```
Unknown system architecture.
WARN (bgl): source/blender/python/generic/bgl.cc:2678 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module.
ERROR INITIALIZING UPDATER
attempted relative import with no known parent package
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/foobar/Library/Application Support/Blender/4.1/scripts/addons/ReSprytile/__init__.py", line 36, in <module>
    from . import sprytile_gui, sprytile_modal, sprytile_panel, sprytile_utils, sprytile_uv, spryTile_addonPref
  File "/Users/foobar/Library/Application Support/Blender/4.1/scripts/addons/ReSprytile/sprytile_gui.py", line 32, in <module>
    import spryTile_OS_EverythingElse
  File "/Users/foobar/Library/Application Support/Blender/4.1/scripts/addons/ReSprytile/spryTile_OS_EverythingElse.py", line 77, in <module>
    flat_shader = gpu.types.GPUShader(flat_vertex_shader, flat_fragment_shader)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Shader Compile Error, see console for more details
```

**Comment by Dan2552** [comment]
I'm not familiar with the codebase, but from here, it looks like it's not a supported platform: https://github.com/ionthedev/ReSprytile/blob/98a2c2c503a074dfb11de309cc27f52cbd7eb14b/sprytile_gui.py#L6-L26
