### ISSUE TITLE
Two errors plus workaround

### ISSUE THREAD

**Issue by BrahRah** [ionthedev/ReSprytile#4]
```
Traceback (most recent call last):
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_modal.py", line 608, in modal
    self.exit_modal(event, context)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_modal.py", line 924, in exit_modal
    self.call_tool(event, False, context)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_modal.py", line 712, in call_tool
    build_preview=self.draw_preview,
  File "/home/r2d2/MyApps/blender-3.6.1-linux-x64/3.6/scripts/modules/bpy_types.py", line 855, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OP_SprytileModalTool' object has no attribute 'draw_preview'
```
```
Traceback (most recent call last):
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_gui.py", line 205, in modal
    ret_val = self.handle_ui(context, event)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_gui.py", line 489, in handle_ui
    tilegrid.tile_selection[0] = sel_min.x
TypeError: expected an int type
Error: Python: Traceback (most recent call last):
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_gui.py", line 205, in modal
    ret_val = self.handle_ui(context, event)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/sprytile-addon-master/sprytile_gui.py", line 489, in handle_ui
    tilegrid.tile_selection[0] = sel_min.x
TypeError: expected an int type
```
The issue I've found is blender outputting floats: <Vector (25.0000, 16.0000)> when it's supposed to be an int.

The workaround is:
sprytile_gui.py:
```
                tilegrid.tile_selection[1] = int(sel_min.y)
                tilegrid.tile_selection[2] = (int(sel_max.x) - int(sel_min.x)) + 1
                tilegrid.tile_selection[3] = (int(sel_max.y) - int(sel_min.y)) + 1
```
and
```
        context.scene.sprytile_ui.palette_pos[0] = int(display_offset.x)
        context.scene.sprytile_ui.palette_pos[1] = int(display_offset.y)
```
That seems to fix both issues but also messes with the padding settings. My assumption is that blender forwards the .000 values from the ui. But I haven't found that part.

**Comment by BrahRah** [comment]
Hmm looks like the padding could be another issue. I've removed the workarounds and the padding issue is still there.

**Comment by BrahRah** [comment]
I just realized that I had the version from: https://github.com/belzecue/ReSprytile 
This version doesn't seem to have the issue.
