### ISSUE TITLE
uv align error

### ISSUE THREAD

**Issue by BrahRah** [ionthedev/ReSprytile#9]
Happens when pressing one of the 9 uv align buttons.
```
Traceback (most recent call last):
  File "/home/r2d2/.config/blender/3.6/scripts/addons/ReSprytile-master/sprytile_modal.py", line 608, in modal
    self.exit_modal(event, context)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/ReSprytile-master/sprytile_modal.py", line 924, in exit_modal
    self.call_tool(event, False, context)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/ReSprytile-master/sprytile_modal.py", line 712, in call_tool
    build_preview=self.draw_preview,
  File "/home/r2d2/MyApps/blender-3.6.1-linux-x64/3.6/scripts/modules/bpy_types.py", line 855, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OP_SprytileModalTool' object has no attribute 'draw_preview'
Error: Python: Traceback (most recent call last):
  File "/home/r2d2/.config/blender/3.6/scripts/addons/ReSprytile-master/sprytile_modal.py", line 608, in modal
    self.exit_modal(event, context)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/ReSprytile-master/sprytile_modal.py", line 924, in exit_modal
    self.call_tool(event, False, context)
  File "/home/r2d2/.config/blender/3.6/scripts/addons/ReSprytile-master/sprytile_modal.py", line 712, in call_tool
    build_preview=self.draw_preview,
  File "/home/r2d2/MyApps/blender-3.6.1-linux-x64/3.6/scripts/modules/bpy_types.py", line 855, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OP_SprytileModalTool' object has no attribute 'draw_preview'

Traceback (most recent call last):
  File "/home/r2d2/.config/blender/3.6/scripts/addons/ReSprytile-master/sprytile_gui.py", line 1742, in draw_callback_handler
    VIEW3D_OP_SprytileGui.draw_to_viewport(self.gui_min, self.gui_max, show_extra,
  File "/home/r2d2/MyApps/blender-3.6.1-linux-x64/3.6/scripts/modules/bpy_types.py", line 851, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type VIEW3D_OP_SprytileGui has been removed
```

**Comment by ionthedev** [comment]
Could you specify what buttons your exactly pressing?

**Comment by BrahRah** [comment]
I've tried to replicate the error again but now the uv align buttons work properly.
